package cn.edu.uestc.shoe.shop.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Test generated by hbm2java
 */
@Entity
@Table(name = "test")
public class Test implements java.io.Serializable {

	private Integer testId;
	private String testName;

	public Test() {
	}
	
	public Test(Integer testId, String testName) {
		this.testId = testId;
		this.testName = testName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "test_id", unique = true, nullable = false)
	public Integer getTestId() {
		return testId;
	}

	public void setTestId(Integer testId) {
		this.testId = testId;
	}

	@Column(name = "test_name", nullable = false, length = 50)
	public String getTestName() {
		return testName;
	}

	public void setTestName(String testName) {
		this.testName = testName;
	}

}
